name: 08-Using-Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVER_WRITTEN: "I will be overwritten"
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'This is a default value' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env"
      OVER_WRITTEN: "I have been overwritten at job level"
    steps:
      - name: Print env variables
        env:
          STEP_VAR: "I am a step env var"
          step_var2: "I am another step env var"
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var2: $step_var2"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten: ${{ env.OVER_WRITTEN }}"

      - name: Overwrite job variable
        env:
          OVER_WRITTEN: "I have been overwritten at step level"
        run: |
          echo "Overwritten at step level: ${{ env.OVER_WRITTEN }}"

  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
          echo "Org var: ${{ vars.ORG_VAR }}"
          echo "Org overwritten var: ${{ vars.ORG_OVERWRITTEN_VAR }}"
          echo "Repo var: ${{ vars.REPOSITORY_VAR }}"

  echo-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print prod variables
        run: |
          echo "Orgs var: ${{ vars.ORG_VAR }}"
          echo "Org overwritten var: ${{ vars.ORG_OVERWRITTEN_VAR }}"
          echo "Repo var: ${{ vars.REPOSITORY_VAR }}"
          echo "Environment var: ${{ vars.TARGET_VAR }}"

  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print undefined variable
        run: |
          echo "Org var: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}"