name: 08-Using-Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVER_WRITTEN: "I will be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env"
      OVER_WRITTEN: "I have been overwritten at job level"
    steps:
      - name: Print env variables
        env:
          STEP_VAR: "I am a step env var"
          step_var2: "I am another step env var"
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var2: $step_var2"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten: ${{ env.OVER_WRITTEN }}"

      - name: Overwrite job variable
        env:
          OVER_WRITTEN: "I have been overwritten at step level"
        run: |
          echo "Overwritten at step level: ${{ env.OVER_WRITTEN }}"